### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by kene-creator** [OmarMWarraich/group-capstone-ror#15]
**Number of participants int the group**
- Two(2)

**Link to project repostory**
[Project Link](https://github.com/OmarMWarraich/group-capstone-ror/projects/1)

**Comment by prolajumokeoni** [comment]
Hello @kene-creator and @OmarMWarraich, I noticed your project link in the issue above navigates to your github repository and not Github project(kanban board), can you please update the project link above to redirect to your   Github project(kanban board)

**Comment by kene-creator** [comment]
Thank you. I'll  do that now

**Comment by kene-creator** [comment]
Already updated, thank you.

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
